name: Ondrej Kavula
favicon: null
layout_spectrum: 0.4449330377392471
typography_spectrum: 0.21312
title: OndrejKavula.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#939194'
    - '#4d4b4e'
    - '#1b1b1d'
    - '#e5a984'
    - '#b6704e'
  brandStrength: 0.663983755512163
  lightness: 0.45017873658798635
  saturation: 0.6539207077585161
  rhythmicContrast: 0.5
purpose: []
