name: OndrejKavula
favicon: null
layout_spectrum: 0.4449330377392471
typography_spectrum: 0.1962609540205449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.663983755512163
  lightness: 0.45017873658798635
  saturation: 0.6539207077585161
  rhythmicContrast: 0.21860318444669247
purpose: []
