name: Ondrej Kavula
favicon: null
layout_spectrum: 0.71585
typography_spectrum: 0.21312
title: OndrejKavula.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212123'
    - '#48484a'
    - '#918f92'
    - '#f1c9b2'
    - '#995645'
  brandStrength: 0.375
  lightness: 0.45017873658798635
  saturation: 0.6539207077585161
  rhythmicContrast: 0.5
purpose: []
